engines:
  pep8:
    enable: true
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3

ratings:
  paths:
  - arca/**
  - "**.py"
