env:
  global:
  - DOCKER_HUB_USERNAME=arcaoss
  - secure: ppGcEBqaGD7z1qq1GvfMs6La/r/ROaaE+ymcfdT1Gmxa3YjjpCxo/W6KwaOcGq7fCxlZdp2gn5fi/p7fY82cDvvFT3pOioVxrzaW8C4CqZDTUtXKLxSpEOnrjuDTm0tHJPnS3ILimi20AAys0lv7Ba06zseZTfIzSmEm8YU7dXZFM6/Ms9YSVNSwof+k5gW628UiEwfHAkKVNhKXiiwVfCvI15oHONZx0fJb1JByBWTYqjtouUl9Yzobo6qK1DCkYa1ZDfhuUgLckiC4cbl6Z59Cy+yvZtcHq5ijTraHu/LKWFO9a+I6Bu0tzSo6HVwa08YQy98gRWKluOvUUalID6NxxBV5KZN67Y9urr6mD5XWwunTjBFXP69w3dMjkAWR2M1Ls7mmS9yd64NhnKZ+cblDEhmGqyf5pcJYYyDq1MwmCRiPHQCWIIJRUqJbteVPn6iRQ3axWDqc3ByCf1DvS4DyWyio+/RU2KxCglVJWkLCBB7MEoFVwiFxkfL/TRcW4h036tGPX0dNCLaa9U931QQQ3EH3GRbAcbSCqS6mEpegUwdwNxcdRGicyB+Jvze2pzKjHa9QnrUaRMYd/8MFta/mCw2rBRZ0PDoogUZqfYbiS/lDKjnpedx7i5l4RuFQdEEWQL/sB/l4pMwE0F740J9bJb4JC+X0EdiQq9PNmxw=
language: python
dist: xenial
python:
- '3.6'
- '3.7'
- '3.8'

cache:
- pip
notifications:
  email: false
sudo: required
services:
- docker
install:
- pip install codecov mypy
- pip install -r requirements.txt  # so travis pip cache can actually cache something
- python setup.py install
before_script:
- 'if [ -n "$DOCKER_HUB_PASSWORD" ]; then docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"; fi'
- 'if [ -z "$DOCKER_HUB_PASSWORD" ]; then export SKIP_PUSH_TEST=true; fi'
script:
- python setup.py test 2>error.log
- mypy arca || echo "Optional MyPy check failed"
after_script:
- cat error.log
- sleep 1
after_success:
- codecov
branches:
  only:
  - master
  - /release-v[0-9]+/
deploy:
  provider: script
  skip_cleanup: true
  script: python setup.py deploy_docker_bases
  on:
    branch: master
    repo: pyvec/arca
    python: '3.7'
